### ISSUE TITLE
Dreamcast KDDI MMBB?

### ISSUE THREAD

**Issue by vkedwardli** [inada-s/zdxsv#37]
Thank you for this amazing project

Is it possible to reuse some component in this project to build the service for Dreamcast Gundam DX?

Or is the implementation completely different?

**Comment by inada-s** [comment]
I think it is not able to reuse components, but the basic server design is similar to GDX one.
I believe the most difficult problem of GDX is how to bypass/emulate modem connection.

**Comment by vkedwardli** [comment]
Sorry would you share how did you create this service?
I've got a working modem connection now, the game is waiting for some server response before sending any data and then timeout and closed the modem connection. Did you reverse engineer this from scratch? Or you have some data dump before the service close? thanks again

**Comment by inada-s** [comment]
I had been played this game while the original server is available.
When closed original server, I've decided to create this private server.
After two years try and error, also thanks to the [obsrv.org](http://obsrv.org/)'s packet capture, I could develop this server.
I don't have any packet dumps.
If you really want to create GDX's private server, I'll help the project.

**Comment by gh0stl1ne** [comment]
I’m tight on time but reviving a DC online title would be interesting. I’d have to get the Gundam game first but I’d help, too.

**Comment by inada-s** [comment]
https://github.com/inada-s/gdxsv

I created a repository for now.
As long as my motivation continues, I will do a survey.

**Comment by vkedwardli** [comment]
thanks a lot! for my initial findings, where should I post to? your new
repo's wiki?

**Comment by inada-s** [comment]
Feel free to use the new repository issues and wikis.
Although there are no particular rules, I think it is not good to continue talking with this close issue.

- https://github.com/inada-s/gdxsv/wiki
- https://github.com/inada-s/gdxsv/issues

Please let me know if you have any inconsistencies in the repository permissions.
